### ISSUE TITLE
Get a report of conflicting responsible role content in the target .docx

### ISSUE THREAD

**Issue by mogul** [opencontrol/fedramp-templater#13]
**Update** Originally, this card was for all the differences. It has been broken out to only focus on the responsible role sections.
The others are
- https://github.com/opencontrol/fedramp-templater/issues/50
- https://github.com/opencontrol/fedramp-templater/issues/51
- https://github.com/opencontrol/fedramp-templater/issues/52

In order make it easier to incorporate of manual downstream edits of the output .docx into the upstream YAML, YAML authors want a report of conflicts between the existing .docx content and content renderable from YAML.

**Acceptance Criteria**
- [ ]  Given a .docx with content in fields that we would render to 
  - AND the existing content conflicts with what we would render
  - WHEN we try to render with the `--diff` flag
  - THEN all the conflicts are reported
  - AND the target .docx is not modified

**Comment by jcscottiii** [comment]
Currently, we can render:
- [x] Responsible Roles
- [ ] Narratives

Do a check on
- [ ] Responsible Roles
- [ ] Narratives

**Comment by mogul** [comment]
(@afeld recently pointed out that this story is about diffing, not linting, so I've changed the description in the BDD above accordingly.)

**Comment by afeld** [comment]
- [x] Split this up into tasks for each field so they are smaller chunks of work.

**Comment by jcscottiii** [comment]
This issue has been split out. This one in particular is closed by https://github.com/opencontrol/fedramp-templater/issues/33
