### ISSUE TITLE
[Spike: 4h] Research how to inject images into Word doc

### ISSUE THREAD

**Issue by jcscottiii** [opencontrol/fedramp-templater#19]
In order to get a better idea of how to handle embedding images into the ssp, we need to see if it's even possible to embed into a word doc. This spike is to test out how feasible it is to do in the current code base and if there are any alternatives / helpers.

Will determine how to tackle https://github.com/opencontrol/compliance-masonry/issues/131

**Comment by jcscottiii** [comment]
Python:
http://python-docx.readthedocs.io/en/latest/user/quickstart.html#adding-a-picture

NodeJs:
https://github.com/open-xml-templating/docxtemplater-image-module

**Comment by jcscottiii** [comment]
https://github.com/python-openxml/python-docx/blob/e784a73bfcdc24ba08f772055f8b4240f420adcf/docs/dev/analysis/features/shapes/picture.rst

**Comment by jcscottiii** [comment]
it can be done!

Empty docx:

![image](https://cloud.githubusercontent.com/assets/7788930/17143240/bec2042e-5320-11e6-8f2f-faa60baf2b17.png)

With picture:

![image](https://cloud.githubusercontent.com/assets/7788930/17143217/a99cbe04-5320-11e6-801b-5cd29e8d31c3.png)

There are some complications. AFAIK, you can't simply replace text with a picture tag. The tags that contain the text, `<w:t>`, cannot have an image tag inside it at all. it will take it literally and render text.

In this case you see you could try one of two things:
1. Go up the hierarchy chain of the tags and delete the `<w:t>` tag.
2. Spoof a new section.
   - Prior to the image section. Close off all the text and section tags. Insert the image tag. Then reopen the text and section tags.

## Additional Information

docx is a glorified .zip file. It contains many files. Until now, we only had to worry about `word/document.xml`, which contains the basic content of the document.

## `word/_rels/document.xml.rels`

This file contains all the relationships for assets for the document file. Even in a blank .docx file, this file is already populated. 

#### Sample

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.png"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/><Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/><Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/>
</Relationships>
```

#### Important parts

The relationship `Id`. and the `Type` and `Target`
- The `Id` will be used to refer to the asset (in our case the image) in the `word/document.xml`.
- The `Type` will refer to the asset type. In our case image.
- The `Target` will refer to the location in the docx archive of where the image is.

#### _rels considerations

When reading the `.docx` file, we need to load up the current relationships and keep a counter on the last used relationship id to make sure we keep unique ids.

## `word/media/*`

All the photos have to be placed in the `word/media` folder of the docx archive.

Each file must have a number on it.
For example:

```
word/media/image1.png
word/media/image2.png
```

**Comment by jcscottiii** [comment]
PR with work here: https://github.com/opencontrol/doc-template/pull/5

**Comment by mogul** [comment]
Research story mission accomplished.
