### ISSUE TITLE
can't find libxml on build

### ISSUE THREAD

**Issue by jcscottiii** [opencontrol/fedramp-templater#2]
![image](https://cloud.githubusercontent.com/assets/7788930/15611589/0924d93a-23f9-11e6-9cf0-277f6e9b71ba.png)

**Comment by afeld** [comment]
Can you run `brew update && brew install libxml2`, and try the build again?

**Comment by jcscottiii** [comment]
it installed libxml2 but no dice still.

![image](https://cloud.githubusercontent.com/assets/7788930/15615540/f8f3e934-240c-11e6-9a34-375ca1a2aa9f.png)

i'm guessing I need to do something to get the stuff into my `/usr/local/include`
