### ISSUE TITLE
Render control_originations

### ISSUE THREAD

**Issue by afeld** [opencontrol/fedramp-templater#26]
https://github.com/opencontrol/schemas#components

Depends on #10.

**Comment by afeld** [comment]
This is going to be a _little_ more complicated that just checking the checkboxes because it's won't necessarily be a direct translation; for example, the combination of `Service Provider Corporate` from one component mixed with `Service Provider ____` from another would make it `Hybrid`.

/cc @brittag

**Comment by brittag** [comment]
Huh, I'd be curious to learn more about how that would work. I'd be hesitant about automatically combining originations - I suspect that sometimes the appropriate thing to do is to check two separate boxes instead of checking the hybrid box.

**Comment by afeld** [comment]
Closed by https://github.com/opencontrol/fedramp-templater/pull/44.
